### ISSUE TITLE
Running inside container is non-functional

### ISSUE THREAD

**Issue by captmiddy** [Trott/solr-proxy#255]
If you run the solr-proxy command inside a container it is non-functional because the fastify module by default uses localhost to bind and localhost in containers do not point to 0.0.0.0.  It would be good to offer an option of proxyHost to allow the listen hostname/ip to be set on startup.  This would allow 0.0.0.0 to be passed as a listen host so that every name is used or to limit the listen host to a single name on a multi-host server.  

I don't yet have a code fix but in the js file this would be in the start command for SolrProxy where port is currently used for listen it would change to server.listen({port: port , host: proxyHost})

**Comment by Trott** [comment]
Fix in https://github.com/Trott/solr-proxy/pull/258. (I used `--host` rather than `--proxyHost` to correspond with `--port`. Does that seem objectionable to you? It would be easy enough to change it or even allow the user to use either option.)

Local testing for me seemed to work. Any chance you're able to apply the PR patch and test in your container before I merge it? Or should I YOLO merge and then you can install it per usual to test?

**Comment by captmiddy** [comment]
I have no objection to the name, I will attempt to use this locally shortly.  I hand-stitched the modification into the application yesterday so I could get it deployed for someone to use.  Everything that I see in the file looks appropriate to the changes necessary to support binding to the host on docker.

**Comment by Trott** [comment]
At the risk of coming across as creepy for noticing Harvard in your GitHub profile and then doing a quick search to find out what department you work in: Hey, if this is being used or potentially will be used for library stuff (or archives stuff), I would love to chat. I maintain this solely so we can use it at UCSF Library for https://industrydocuments.ucsf.edu/ and if another library or archive is using it (or considering using it), I'd love to know more. (My email is in my GitHub profile if you want to not use this issue as a chat board.)

**Comment by captmiddy** [comment]
I do work for Harvard Library Technology Services and we are using this as a proxy to our Solr environment in a production space as of earlier this week.  We use it to mediate access to our text index for paged turned objects from our preservation system (scans of books and manuscripts...) 

I am going to post another ticket in a moment though, as I noticed that the port is not mapped to listenPort in the argv settings meaning that when I pass in port at the command line and have the application in debug mode, I do not get my settings back but the default port of 8008.  I do see where you map host to listenHost so that should be good, which is actually what drew me to the issue of port.  I will do a couple tests hopefully this afternoon and I will let you know if everything is working.  I have a few other big tasks I am working on this morning so it may not happen today as I would hope.

**Comment by Trott** [comment]
I went ahead and landed the proposed fix. I recommend updating to the resulting new version (9.1.0) as doing so might also incidentally update a dependency to resolve a CVE (if you don't already have the updated version of the dependency installed).

(I would also love to compare academic-library-IT notes some time, but that's a different topic.)
